language: java
jdk:
- oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - 51101661@qq.com
  on_success: always
  on_failure: always
branches:
  only:
  - master
before_install:
- export BUILD_NAME=$TRAVIS_BRANCH-$(date -u "+%Y%m%d%H%M%S")-$TRAVIS_BUILD_NUMBER
script:
- sh travis_scripts/tag_build.sh
- sh travis_scripts/build_services.sh
- sh travis_scripts/deploy_to_docker_hub.sh
env:
  global:
  - secure: ohdYiVHgk2P0sxdY9wmcmziughLyE0Q1DzPqiw8WAWVb7xuHK2jbN0lx+HEmpu/kQVubgz8eaqNo62RcSOyzYBMR9NvUDVlMzwQTz6768ZHldnqkw2sZcDCPKXxI/Nl/MC0fafkf0BKH9oJyZyKlOcU1y+NPYw5SZfCja8ifwkcS4Jh3fUcUxRJmmcJsvh799beeLsHdmJLHjyxADypSULMi1cdgyJ5OuRF8i/rhH4pi8fX0kUlM7oSkNb/873vyrMEDZPLaxtbu9+xjLiaKdjvvREQ0KJeJ2wTUmeo5fQqrataFfwSwm/zViecK9bJEf676hPU7F9sYQzUkzjVzLGwslvK3Q5kIzM9uZsHt4WDkwc4ZYlJ8/NEh/xV0Tf2CDSzKAwgjtiuGvRF5DYyQiEq6cg6fIzhq0/+41EYgMwTuT1X5YXx7KycmvcI5mRfeSQ04NUeiA89o2rmDKd1LgA5cBjTQcUncQ5Z4tkoQoBrwEUonphZRi4odU6cNKPc3DJYjz5yqSMIkj5hTXaHueuSXgNiPaOjIhE41LTeKm8BcWJ4i2YTDUpLFoRF1y2ktT7HqSQU26advdfl3o5Asu+DAzkyN7/gNu+L4kvDh+WAl1/sxv/8PVwjuoRrQ7e24fLTT5K1OBMqCWx7yRHf/VD+6xp3tGmVjQVQaPrP8fuI=
  - secure: 3ZaOnz8hTr2zLyYWQT0F39OCn3mQYaYj2imS+rpZ2biHIQJHBb352vChHEajj7UDCPd473y2cW0Z/9HJxQlYRyF2luJQAT92Gdf775huPd/Ixb78d0eeuwCRgcXgqNg7Cd8u5HMTifKOEc6oa/RYRI3WNQ3WaVObcw6MiQPeLpr22Di9zbCnfbfYsZ6eO28McWcT43VuGwaLk6r8LMJg1lL9EgYa0pYzjf42ZDe7AQz6tKcIvbumcKt9M7yauIrGXnFuQ5Xpg2g+IGX32XO6cv/JL3AufypD6QKnYAHfQfq+R2Pwtf8frQZsC8w7arYWVTZEtS71/IBxcrA2QRBZ2DJfhi/9TYrbPXPhnDJxZmV11f8MKaFZy1ehhi7DRejyNUYM8QBAQcjg3XVjc1r1LWgnrBdRityi1ofkOKQ6SBRVYQXBl15RYIBLH4IPk6VHTqr0vau8HU2K5afDMvNfy3lDR8lFsn7So0X4F5Jn2liC1mBmO+Qtq7vTO/eVF6xVsIQyFT4w/p7TBaCn3pAR53yO59VvAXZuZ0nhsdmX18PMBpU1kxsjDrvwiGjoVP4FiUQZGZKbPGMhH2EWlcVTEP8uoQ1M83L5Fj4ntk/0O3p14e3M8hf3d5RhB8aaZnZ/hYmVtReMu91jO0U9zUUSz5HxXsaOh6B3SCkXe9Usdhg=
  - secure: B5WtiBlrUMD3QWjyrcWWQ3X4bMwK5wOWJQo15o3MTOLH85EwZHOmabh8RVoaJn2OOsXyZSfRKZLkdOioFP5ljNnpiQ7GoVU9FfEcyGfvuJiWWXmlBmDrlk/rVk2geJVWeGhCdXqkia7zP+QDdrGxQ+TRepH/CW2t1cFpV++VOSnUFDBMEqp0JzVVhI8kP8t899XtOYOUXYLr9NNaakmzTRLTjF3VXXiHrKc3Ak0IL/phZxrVfJJhjSXqxEzqqFuppPZxEjFnEraNwZR4nVuGnSJZ3b0WexOhQwQ5bRgPoCsCvcZJC+ZJ0ODoOlvVKQSEwo9fU33RpKX1FrZEwImflE20Zvs1aEGDBR24TSTSQwMbgUhtilHeGakmfcnedZeM4INHFWmX8bWPiq9oBwtmCgRDCIiW+3XCJDMCMos1AbZdOwNLNCrCfJVk/MmF8wwYTwCXxB0ubJGtbEEBQpSKe0x1wpz625oMrFR3lIFU1ETyS/KcOwsXhKRN4leCMCiZht49fWms5jT8aj8C+Evk4jO0hmXAZVwGj/o83i1VaepQh0GMzmOZYBNrlP7Zc7+GwDnibrGY4nEWwQbTHI4atVuUNTGlbLXioixtc6VKmSebgKWa/A/Au35qH9BVvkZZ+/bdeMQPIvB+0Rnl5Cz2cz+HLSX3adJcpe9anI2fHLY=
